im:
    resource: "@ImBundle/Controller/"
    type:     annotation
    prefix:   /im
    host:     

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    #prefix:   /{_locale}
    host:      demo.yeskn.com
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     yeskn.com

service:
    resource: "@ServiceBundle/Controller/"
    type:     annotation
    host:     service.yeskn.com
    prefix:   /

#blog:
#    resource: "@BlogBundle/Controller/"
#    type:     annotation
#    #host:     blog.yeskn.com
#    prefix:   /blog

