services:
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: [ '@service_container', '@twig' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }