<?php
/**
 * Created by PhpStorm.
 * User: Jake
 * Date: 2016/5/19
 * Time: 14:00
 */

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;


class ChangePasswordType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('oldPassword','password');
        $builder->add('newPassword','repeated',array(
            'type' => 'password',
            'invalid_message' => 'the password files must be match',
            'required' => true,
            'first_options' => array('label' => 'Password'),
            'second_options'   => array('label' => 'Repeat Password'),
        ));
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Form\Model\ChangePassword',
        ));
     //   parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return 'change_password';
        //return parent::getName(); // TODO: Change the autogenerated stub
    }
}